Support merging PRs automatically if enabled in repository configurations
pleo-io/file-distributor pull request #171
Opened 2023-07-25 11:21 UTC by andersfischernielsen

2023-07-25 11:28 UTC, LittleGreenYoda42 commented on src/git.ts
> +    if (!pullRequestNumber) return false
Do we just want to return false if there is no PR number?

I would suggest to throw an error if we don't expect that to happen or at least log a warning.

This feels like a situation where we will wonder why it suddenly stopped working because there was a change and suddenly the number is undefined.

2023-07-25 11:33 UTC, andersfischernielsen commented on src/git.ts
> +    if (!pullRequestNumber) return false
We definitely do expect that to happen 😄 If the changes in the configuration will lead to no files changed, there's no need to create the PR - hence the PR number will be `undefined`.

2023-07-25 12:26 UTC, danieldisu approved these changes

2023-07-25 13:44 UTC, LittleGreenYoda42 requested changes

2023-07-25 13:44 UTC, LittleGreenYoda42 commented on src/git.ts
> +    if (!pullRequestNumber) return false
I would make the pullRequestNumber mandatory and move the check for it to be defined out to make it more obvious what is happening.

2023-07-25 13:44 UTC, LittleGreenYoda42 commented on src/file-creation.ts
> +    if (combined.automerge) mergePR(repository, pullRequestNumber)
I would rather add another condition to the if for checking that the pullRequestNumber is defined. That way it is more obvious that it could be undefined and nothing would happen in that case. We could also have some helper like `needsAutoMerge`.

2023-07-26 06:03 UTC, andersfischernielsen commented on src/git.ts
> +    if (!pullRequestNumber) return false
Done!

2023-07-26 07:48 UTC, LittleGreenYoda42 commented on src/git.ts
> +    if (!pullRequestNumber) return false
Thanks :+1:

2023-07-26 07:48 UTC, LittleGreenYoda42 approved these changes

2023-07-26 07:50 UTC, LittleGreenYoda42 commented on src/file-creation.ts
> +    if (combined.automerge && pullRequestNumber !== undefined) mergePR(repository, pullRequestNumber)
What do you think about moving this down to after the logging has happened. Right now it say "merged pr" and after that it committed the files. Just reading the logs this could be confusing.

2023-07-26 07:51 UTC, LittleGreenYoda42 commented on src/file-creation.ts
> +    if (combined.automerge && pullRequestNumber !== undefined) mergePR(repository, pullRequestNumber)
Sorry for not bringing this up earlier. I just had another look at the code 😬

2023-07-26 08:34 UTC, marcos-arranz approved these changes

2023-07-26 08:42 UTC, merged